package me.qleek.core.services.bleinterface;

public interface QleekPlayerBLEConnectionServiceInterface {

    // to create an Intent to launch the service, use
    // Intent i = new Intent().setClassName(QleekPlayerBLEConnectionServiceInterface.LAUNCH_INTENT_PACKAGE_NAME, QleekPlayerBLEConnectionServiceInterface.LAUNCH_INTENT_CLASS_NAME);
    String LAUNCH_INTENT_PACKAGE_NAME = "me.qleek.core.services.ble";
    String LAUNCH_INTENT_CLASS_NAME = "me.qleek.core.services.ble.QleekPlayerBLEConnectionService";

    // intents emitted by the service
    String ACTION_CONNECTING_TO_DEVICE = "me.qleek.core.intents.ACTION_CONNECTING_TO_DEVICE";
    String ACTION_CONNECTED_TO_DEVICE = "me.qleek.core.intents.ACTION_CONNECTED_TO_DEVICE";
    String ACTION_CONNECTED_TO_DEVICE_EXTRA_SHOULD_RESET = "me.qleek.core.intents.ACTION_CONNECTED_TO_DEVICE_EXTRA_SHOULD_RESET";
    String ACTION_CONNECTION_TO_DEVICE_FAIL = "me.qleek.core.intents.ACTION_CONNECTION_TO_DEVICE_FAIL";
    String ACTION_CONNECTION_TO_DEVICE_TIMEOUT = "me.qleek.core.intents.ACTION_CONNECTION_TO_DEVICE_TIMEOUT";
    String ACTION_DISCONNECTED_FROM_DEVICE = "me.qleek.core.intents.ACTION_DISCONNECTED_FROM_DEVICE";
    String ACTION_TAG_ON = "me.qleek.core.intents.ACTION_TAG_ON";
    String ACTION_TAG_ON_DATA_TAGID = "me.qleek.core.intents.ACTION_TAG_ON_DATA_TAGID";
    String ACTION_TAG_OFF = "me.qleek.core.intents.ACTION_TAG_OFF";
    String ACTION_BUTTONPRESSED = "me.qleek.core.intents.ACTION_BUTTONPRESSED";
    String ACTION_BUTTONPRESSED_DATA_STATE = "me.qleek.core.intents.ACTION_BUTTONPRESSED_DATA_STATE";

    // states for updating the player display during the setup (message MSG_CHANGE_SETUP_PHASE)
    int ADAPTER_STATE_IDLE = 0x01;
    int ADAPTER_STATE_DISPLAY_INFO = 0x02;
    int ADAPTER_STATE_SHOULD_RESET_ADAPTER = 0x03;
    int ADAPTER_STATE_SHOULD_RESET_PLAYER = 0x04; // followed by 0x42 0x42
    int ADAPTER_STATE_PLAYER_LAUNCH_RESULT = 0x05;

    int ADAPTER_STATE_DISPLAY_INFO_LED_1_FIXED = 0x01;
    int ADAPTER_STATE_DISPLAY_INFO_LED_2_FIXED = 0x02;
    int ADAPTER_STATE_DISPLAY_INFO_LED_3_FIXED = 0x04;
    int ADAPTER_STATE_DISPLAY_INFO_LED_4_FIXED = 0x08;
    int ADAPTER_STATE_DISPLAY_INFO_LED_5_FIXED = 0x10;
    int ADAPTER_STATE_DISPLAY_INFO_LED_6_FIXED = 0x20; // LEDs around Qleek
    int ADAPTER_STATE_DISPLAY_INFO_LED_1_BLINKING = ADAPTER_STATE_DISPLAY_INFO_LED_1_FIXED << 6;
    int ADAPTER_STATE_DISPLAY_INFO_LED_2_BLINKING = ADAPTER_STATE_DISPLAY_INFO_LED_2_FIXED << 6;
    int ADAPTER_STATE_DISPLAY_INFO_LED_3_BLINKING = ADAPTER_STATE_DISPLAY_INFO_LED_3_FIXED << 6;
    int ADAPTER_STATE_DISPLAY_INFO_LED_4_BLINKING = ADAPTER_STATE_DISPLAY_INFO_LED_4_FIXED << 6;
    int ADAPTER_STATE_DISPLAY_INFO_LED_5_BLINKING = ADAPTER_STATE_DISPLAY_INFO_LED_5_FIXED << 6;
    int ADAPTER_STATE_DISPLAY_INFO_LED_6_BLINKING = ADAPTER_STATE_DISPLAY_INFO_LED_6_FIXED << 6;  // LEDs around Qleek

    int ADAPTER_STATE_DISPLAY_INFO_LEDSTATE_TURNING_AP_ON = ADAPTER_STATE_DISPLAY_INFO_LED_1_FIXED | ADAPTER_STATE_DISPLAY_INFO_LED_2_BLINKING;
    int ADAPTER_STATE_DISPLAY_INFO_LEDSTATE_CONNECTING_TO_WIFI = ADAPTER_STATE_DISPLAY_INFO_LED_1_FIXED | ADAPTER_STATE_DISPLAY_INFO_LED_2_FIXED | ADAPTER_STATE_DISPLAY_INFO_LED_3_BLINKING;
    int ADAPTER_STATE_DISPLAY_INFO_LEDSTATE_CONNECTED_TO_WIFI = ADAPTER_STATE_DISPLAY_INFO_LED_1_FIXED | ADAPTER_STATE_DISPLAY_INFO_LED_2_FIXED | ADAPTER_STATE_DISPLAY_INFO_LED_3_FIXED;
    int ADAPTER_STATE_DISPLAY_INFO_LEDSTATE_REGISTERING = ADAPTER_STATE_DISPLAY_INFO_LED_1_FIXED | ADAPTER_STATE_DISPLAY_INFO_LED_2_FIXED | ADAPTER_STATE_DISPLAY_INFO_LED_3_FIXED | ADAPTER_STATE_DISPLAY_INFO_LED_4_BLINKING;

    int ADAPTER_STATE_DISPLAY_INFO_LEDSTATE_UPDATING_ADAPTER = ADAPTER_STATE_DISPLAY_INFO_LED_5_BLINKING;

    // values received when buttons are pressed
    int PLAYER_BTN_F1 =        0x01;
    int PLAYER_BTN_BACK =      0x02;
    int PLAYER_BTN_PLAYPAUSE = 0x04;
    int PLAYER_BTN_FWD =       0x08;
    int PLAYER_BTN_F2 =        0x10;

    // messages to control the service
    int MSG_START_DISCOVERY = 1;
    int MSG_SET_ACTIVE_BUTTONS = 2;
    int MSG_CHANGE_SETUP_PHASE = 3;

}
